Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

В частности, определить оба произведения  A⋅B  и  B⋅A  можно только в случае, когда число столбцов  A  совпадает с числом строк  B , а число строк  A  совпадает с числом столбцов  B . В этом случае матрицы  A⋅B  и  B⋅A  будут квадратными. Их порядок в общем случае будет различным и будет совпадать только в случае квадратных матриц  A  и  B .

Под данное определение попадает вариант г) 𝐴 — квадратная матрица 4×4 , 𝐵 — квадратная матрица 4×4 . Итоговая матрица будет 4x4


Если же не учитывать определенности двух матриц, то для вараинта б) проиведение матриц BA даст новую матрицу 5x5 ; в) произведение матриц AB даст матрицу 8x8 , а происзвдение матриц BA даст матрицу 3x3

2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

Сложим матрицы

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5 
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5 
\end{pmatrix}.$$

Перемножим матрицы 

$$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \; и \; B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$$

$$A\cdot B=\begin{pmatrix}
1\cdot4-2\cdot0 & 1\cdot-1-2\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot-1+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$$

In [25]:
import numpy as np

In [26]:
a = np.array([[1,-2],[3,0]])
b = np.array([[4,-1],[0,5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')
print(f'Матрица AB\n{a.dot(b)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} 
-2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1 
\end{pmatrix} 
+4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} 
+\begin{pmatrix}
0 & -10\\ 
-4 & 2 
\end{pmatrix} 
+\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$$

In [27]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

print(f'Матрица А\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица C\n{c}\n')
print(f'Матрица 3*А\n{3 * a}')
print(f'Матрица -2*B\n{-2 * b}')
print(f'Матрица 4*C\n{4 * c}')
print(f'Итоговая матрица \n{(3 * a)+(-2 * b)+(4 * c)}')

Матрица А
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица C
[[ 2 -4]
 [ 1  1]]

Матрица 3*А
[[  3  21]
 [  9 -18]]
Матрица -2*B
[[  0 -10]
 [ -4   2]]
Матрица 4*C
[[  8 -16]
 [  4   4]]
Итоговая матрица 
[[ 11  -5]
 [  9 -12]]


_4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}, \;A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3 
\end{pmatrix}.$$

$$A\cdot A^{T}=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot-2 & 4\cdot2+1\cdot3\\ 
5\cdot4-2\cdot1 & 5\cdot5-2\cdot-2 & 5\cdot2-2\cdot3\\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot-2 & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}.$$

$$A^{T}\cdot A=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot-2+2\cdot3\\ 
1\cdot4-2\cdot5+3\cdot2 & 1\cdot1-2\cdot-2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}.$$

In [28]:
a = np.array([[4, 1], [5, -2], [2, 3]])
at = a.T

print(f'Матрица А\n{a}\n')
print(f'Матрица A транпонированная\n{at}\n')
print(f'Матрица A*A транпонированная\n{a.dot(at)}')
print(f'Матрица A транпонированная * A\n{at.dot(a)}')

Матрица А
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Матрица A транпонированная
[[ 4  5  2]
 [ 1 -2  3]]

Матрица A*A транпонированная
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A транпонированная * A
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

#m1 = input('Введите число строк 1 матрицы')
#n1 = input('Введите число столбцов 1 матрицы')
#m2 = input('Введите число строк 2 матрицы: ')
#n2 = input('Введите число столбцов 2 матрицы: ')
#print(f'У нас будут представлены матрицы {m1}x{n1} и {m2}x{n2}')
#n1 = 2
#m1 = 2
#scalar_proinv = 0
#matr_proizv = []
#if n1 == m1:
#    for ind, vector in matr1:
#        for ind2, elm in vector:
#            scalar_proinv += elm * matr2[ind][ind2]
#        matr_proizv.append(scalar_proizv)
    
#    строка из первой матрицы определеят строку элемента
#    колонка второй матрицы определяет колонку элемента


Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

а) Если x = 0
(sin x * sin x) - (-cos x * cos x) = 0 * 1 - (-1*1) = 1

б) $$\begin{vmatrix}
4 & 2 & 3 \\ 
0 & 5 & 1 \\  
0 & 0 & 9\\ 
\end{vmatrix} = 4\cdot(5\cdot9-1\cdot0) - 2\cdot(0\cdot9 - 1\cdot0) + 3\cdot(0\cdot0-5\cdot0)= 180$$

в) $$\begin{vmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\  
7 & 8 & 9\\ 
\end{vmatrix} = 1\cdot(5\cdot9-6\cdot8) - 2\cdot(4\cdot9 - 6\cdot7) + 3\cdot(4\cdot8-5\cdot7)= 0$$

In [29]:
import scipy.linalg

In [30]:
x = 0
a = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Матрица:\n{b}')
print(f'Матрица:\n{c}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')
print(f'Определитель:\n{np.linalg.det(c):.0f}')

Матрица:
[[ 0. -1.]
 [ 1.  0.]]
Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
1
Определитель:
180
Определитель:
0


2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а)  $det(A^{2})= 16$;

б)  $$detA^{T}=detA=4.$$

в)  Если все элементы строки (столбца) умножить на одно и тоже число, то определитель умножится на это число. 𝑑𝑒𝑡(2𝐴) = 8 .

3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.

$$\begin{vmatrix}
-2 & 7 & -3 \\ 
4 & -14 & 6 \\  
-3 & 7 & 13\\ 
\end{vmatrix} = -2\cdot(-14\cdot13-6\cdot7)) - 7\cdot(4\cdot13 - 6\cdot-3) + 3\cdot(4\cdot7-(-14\cdot-3))= 0$$

In [31]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) вычтем из 2 и 3 строки 1 усноженную на 1 и на 2 соответсвенно

$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & -1 & -2
\end{pmatrix}.$$

Если домножить 2 строку -1 и рибавить её к 3 строке то полуим матрицу ранг которой равен 2

$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}.$$

б) Поскольку в матрице есть ненулевые элементы, то её ранг не менее 1. В матрице четыре строки и четыре столбца. Минимальная размерность – четыре, следовательно, ранг данной матрицы заведомо не превзойдёт 4.

Проверку миноров 2-го порядка начинаем с так называемого углового минора
$$\begin{vmatrix}
0 & 0  \\ 
0 & 0 
\end{vmatrix} = 0$$

$$\begin{vmatrix}
0 & 2  \\ 
0 & 2 
\end{vmatrix} = 0$$

$$\begin{vmatrix}
0 & 1  \\ 
0 & 2 
\end{vmatrix} = 0$$

$$\begin{vmatrix}
0 & 2  \\ 
0 & 2 
\end{vmatrix} = 0$$

$$\begin{vmatrix}
2 & 1  \\ 
2 & 2 
\end{vmatrix} = 4 - 2 = 2$$   не равен нулю значит, ранг матрицы не менее двух.


$$\begin{vmatrix}
0 & 2 & 1 \\ 
0 & 2 & 2\\
0 & 4 & 3
\end{vmatrix} = 3 * \begin{vmatrix}
0 & 2\\ 
0 & 2
\end{vmatrix} + 
\begin{vmatrix}
0 & 2\\ 
0 & 4
\end{vmatrix} = 0 $$


ранг матрицы два.


In [32]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
с =  np.array([[1, 2, 3]])
ra = np.linalg.matrix_rank(a)
rb = np.linalg.matrix_rank(b)
rc = np.linalg.matrix_rank(c)
print(f'Ранг матрицы A: {ra}')
print(f'Ранг матрицы B: {ra}')
print(f'Ранг матрицы B: {rc}')

Ранг матрицы A: 2
Ранг матрицы B: 2
Ранг матрицы B: 2
