__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$


# $$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)-2\cdot(-6)=0,$$
$$(-6-6\lambda+\lambda+\lambda^{2}+12)=0,$$
$$(\lambda^{2}-5\lambda+6)=0,$$

Собственные значения
$$\lambda=2.$$ $$\lambda=3.$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
a & b\\ 
c & d
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
ax_{1}+bx_{2}=\lambda x_{1}, \\
cx_{1}+dx_{2}=\lambda x_{2}.
\end{cases}$$ 

Перенеся все в левую часть, получим

$$\begin{cases}
-x_{1}-6\cdot x_{2} - 2\cdot x_{1} = 0, \\
2\cdot x_{1}+6 \cdot x_{2} - 2\cdot x_{2} = 0;
\end{cases}$$ 

$$\begin{cases}
-3 \cdot x_{1} - 6\cdot x_{2} = 0, \\
2\cdot x_{1} + 4\cdot x_{2} = 0.
\end{cases}$$

$$\begin{cases}
x_{1} = - 2\cdot x_{2}.
\end{cases}$$

Если x2 = -1, то x1 = 2

первый собственный вектор вида $x=\begin{pmatrix}
2\\ 
-1
\end{pmatrix}$ 

Для второго собственного значения получим

$$\begin{cases}
-x_{1}-6\cdot x_{2} - 3\cdot x_{1} = 0, \\
2\cdot x_{1}+6 \cdot x_{2} - 3\cdot x_{2} = 0;
\end{cases}$$ 

$$\begin{cases}
x_{1} = - 3/2\cdot x_{2}.
\end{cases}$$

Если x2 = -2, то x1 = 3

второй собственный вектор вида $x=\begin{pmatrix}
3\\ 
-2
\end{pmatrix}$ 

In [24]:
# запустите последовательно код в ячейках,чтобы отобразить иллюстрации
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [25]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')


Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


_2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

# $$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)^{2}=0,$$

Собственные значения
$$\lambda=-1.$$

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Из этого будет следовать, что 

$$\begin{cases}
-1+0=1\cdot\lambda \\ 
0-1 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-1\\ 
\lambda=-1
\end{cases}.$$

Такая система имеет смысл, следовательно, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$. Рот этом найденное значение $\lambda$ совпало с найденным ранее и равно - 1

In [26]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Из этого будет следовать, что 

$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

Такая система имеет смысл, следовательно, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$.

In [27]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

Предположим, что вектор $x$ является собственным вектором заданного линейного оператор:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
3 \dot \lambda=-9\\ 
-3 \dot \lambda=9\\
-4 \dot \lambda=-12
\end{cases}
\Rightarrow
\lambda=3 и \lambda=-3.$$

Такая система не имеет смысла, следовательно, вектор  x=(3,−3,-4)  не является собственным вектором линейного оператора, заданного матрицей  A .

In [28]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]
